package event

// Available fields for an event.
const (
	// All will return all available fields.
	FieldAll                              = "*"
	FieldBody                             = "body"
	FieldCategory                         = "category"
	FieldGroupContentAccess               = "group_content_access"
	FieldOgGroupRef                       = "og_group_ref"
	FieldOgGroupRequest                   = "og_group_request"
	FieldDateTime                         = "date_time"
	FieldImage                            = "image"
	FieldPrice                            = "price"
	FieldEmail                            = "email"
	FieldLink                             = "link"
	FieldOffline                          = "offline"
	FieldPhone                            = "phone"
	FieldTopic                            = "topic"
	FieldTitleField                       = "title_field"
	FieldPriceCategory                    = "price_category"
	FieldEventStatus                      = "event_status"
	FieldFlyer                            = "flyer"
	FieldOgMembership                     = "og_membership"
	FieldOgGroupRefOgMembership        = "og_group_ref__og_membership"
	FieldOgGroupRequestOgMembership    = "og_group_request__og_membership"
	FieldNid                              = "nid"
	FieldVid                              = "vid"
	FieldIsNew                           = "is_new"
	FieldEntityType                      = "type"
	FieldTitle                            = "title"
	FieldLanguage                         = "language"
	FieldUrl                              = "url"
	FieldEditUrl                         = "edit_url"
	FieldStatus                           = "status"
	FieldPromote                          = "promote"
	FieldSticky                           = "sticky"
	FieldCreated                          = "created"
	FieldChanged                          = "changed"
	FieldFeedNid                         = "feed_nid"
	FieldFlagAbuseNodeUser                = "flag_abuse_node_user"
	FieldFlagAbuseWhitelistNodeUser       = "flag_abuse_whitelist_node_user"
	FieldUUID                             = "uuid"
	FieldVUUID                            = "vuuid"
)
