package group

// Available fields for a group.
const (
	// All will return all available fields.
	FieldAll                        = "*"
	FieldBody                       = "body"
	FieldCategory                   = "category"
	FieldGroupGroup                 = "group_group"
	FieldGroupLogo                  = "group_logo"
	FieldImage                      = "image"
	FieldEmail                      = "email"
	FieldLink                       = "link"
	FieldOffline                    = "offline"
	FieldOpeningTheme               = "opening_times"
	FieldPhone                      = "phone"
	FieldTopic                      = "topic"
	FieldNotifications              = "notifications"
	FieldActive                     = "active"
	FieldFlyer                      = "flyer"
	FieldMembers                    = "members"
	FieldMembers1                   = "members__1"
	FieldMembers2                   = "members__2"
	FieldMembers3                   = "members__3"
	FieldRadarGroupListedBy         = "radar_group_listed_by"
	FieldNid                        = "nid"
	FieldVid                        = "vid"
	FieldIsNew                      = "is_new"
	FieldType                       = "type"
	FieldTitle                      = "title"
	FieldLanugage                   = "language"
	FieldUrl                        = "url"
	FieldEditUrl                    = "edit_url"
	FieldStatus                     = "status"
	FieldPromote                    = "promote"
	FieldSticky                     = "sticky"
	FieldCreated                    = "created"
	FieldChanged                    = "changed"
	FieldFeedNid                    = "feed_nid"
	FieldFlagAbuseNodeUser          = "flag_abuse_node_user"
	FieldFlagAbuseWhitelistNodeUser = "flag_abuse_whitelist_node_user"
	FieldUUID                       = "uuid"
	FieldVUUID                      = "vuuid"
)
